# Generated by Django 5.2.5 on 2025-08-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('price', models.FloatField()),
                ('transactionId', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('menuItemIds', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
